image: Visual Studio 2017

configuration:
  - Debug
  
clone_folder: c:\projects\proj

cache:		
  - c:\projects\build1\vcpkg\scripts -> appveyor.yml		
  - c:\projects\build1\vcpkg\installed -> appveyor.yml
 
platform:
- x86

install:  
  - ps: If ($env:Platform -Match "x86"){ $env:CMAKE_ARCH="" } Else { $env:CMAKE_ARCH=" Win64"}
  - cd c:\projects
  - IF NOT EXIST c:\projects\build1 mkdir build1
  - cd build1
  - IF NOT EXIST c:\projects\build1\vcpkg git clone https://github.com/Microsoft/vcpkg
  - cd vcpkg
  - IF NOT EXIST c:\projects\build1\vcpkg\installed\x86-windows powershell -exec bypass scripts\bootstrap.ps1
  - IF NOT EXIST c:\projects\build1\vcpkg\installed\x86-windows .\vcpkg install libjpeg-turbo zlib openssl
  - cd c:\projects\proj
  - mkdir build
  - cd build
  - cmake "-DCMAKE_TOOLCHAIN_FILE=c:\projects\build1\vcpkg\scripts\buildsystems\vcpkg.cmake" .. 
  
build_script:
  - cmake --build .
  
test_script:
  - ctest -V -C Debug 
