image: Visual Studio 2017

configuration:
  - Release
  
clone_folder: c:\projects\proj

platform:
- x86

install:  
  - ps: wget https://download.microsoft.com/download/7/9/6/796EF2E4-801B-4FC4-AB28-B59FBF6D907B/VCForPython27.msi -outfile "VCForPython27.msi"
  - start /wait msiexec /i c:\projects\proj\VCForPython27.msi /quiet /qn /norestart
  - pip install autobahntestsuite
  - ps: If ($env:Platform -Match "x86"){ $env:CMAKE_ARCH="" } Else { $env:CMAKE_ARCH=" Win64"}
  - cd c:\projects
  - set CMAKE_URL="https://cmake.org/files/v3.9/cmake-3.9.3-win64-x64.zip"
  - appveyor DownloadFile %CMAKE_URL% -FileName cmake.zip
  - 7z x cmake.zip -oC:\projects\cmake > nul
  - move C:\projects\deps\cmake-* C:\projects\deps\cmake # Move to a version-agnostic directory
  - set PATH=C:\projects\deps\cmake\bin;%PATH%
  - cmake --version
  - mkdir build
  - cd build
  - git clone https://github.com/Microsoft/vcpkg
  - cd vcpkg
  - powershell -exec bypass scripts\bootstrap.ps1
  - .\vcpkg integrate install
  - .\vcpkg install zlib:x86-windows-static libjpeg-turbo:x86-windows-static openssl:x86-windows-static zlib openssl libjpeg-turbo

    
build_script:
  - cd c:\projects\proj
  - mkdir build
  - cd build
  - cmake -DBUILD_SHARED_LIBS=OFF -DVCPKG_TARGET_TRIPLET=x86-windows-static "-DCMAKE_TOOLCHAIN_FILE=c:\projects\build\vcpkg\scripts\buildsystems\vcpkg.cmake" .. 
  - cmake --build .
  - ctest -V -C Release
  - cmake -DBUILD_SHARED_LIBS=ON "-DCMAKE_TOOLCHAIN_FILE=c:\projects\build\vcpkg\scripts\buildsystems\vcpkg.cmake" .. 
  - cmake --build .
  - cmake --build .
  - ctest -V -C Release

